version: '2'

services:

  ########################
  ## BEANSTALKD CONSOLE ##
  ########################

  pb-beanstalkd-console:
    container_name: 'pb-beanstalkd-console'
    depends_on:
      - 'pb-beanstalkd'
    image: 'schickling/beanstalkd-console'
    ports:
      - '2080:2080'

  ################
  ## BEANSTALKD ##
  ################

  pb-beanstalkd:
    container_name: 'pb-beanstalkd'
    image: 'schickling/beanstalkd'
    ports:
      - '11300:11300'

  ###############
  ## BG WORKER ##
  ###############

  pb-bg-worker:
    command: 'perl bg_worker.pl daemon --nodaemonize --verbose --watch=bg_pubsub'
    container_name: 'pb-bg-worker'
    depends_on:
      - 'pb-websocket'
    image: 'perlblue/pb-server'
    volumes:
        - ./bin:/home/perlblue/pb-server/bin
        - ./docs:/home/perlblue/pb-server/docs
        - ./etc:/home/perlblue/pb-server/etc
        - ./log:/home/perlblue/pb-server/log
        - ./lib:/home/perlblue/pb-server/lib
        - ./t:/home/perlblue/pb-server/t
        - ./var:/home/perlblue/pb-server/var


  ################
  ## MYSQL DATA ##
  ################

  pb-mysql-data:
    command: '/bin/bash'
    container_name: 'pb-mysql-data'
    image: 'arungupta/mysql-data-container'

  ##################
  ## MYSQL SERVER ##
  ##################

  pb-mysql-server:
    container_name: 'pb-mysql-server'
    depends_on:
      - 'pb-mysql-data'
    environment:
      - 'MYSQL_ROOT_PASSWORD=perlblue'
    image: 'mysql:5.5'
    volumes_from:
      - 'pb-mysql-data'

  ###########
  ## NGINX ##
  ###########

#  pb-nginx:
#    build:
#      context: .
#      dockerfile: ./docker/build-nginx/Dockerfile
#    container_name: 'pb-nginx'
#    depends_on:
#      - 'pb-websocket'
#    image: 'perlblue/pb-nginx'
#    ports:
#      - '8080:80'
#      - '8443:443'
#    volumes:
#      - ./etc/nginx.conf:/etc/nginx/nginx.conf
#      - ./etc:/home/perlblue/pb-server/etc
#      - ./var:/home/perlblue/pb-server/var
#      - ./log:/home/perlblue/pb-server/log
#      - ./var/www/public/api/api.css:/home/perlblue/pb-server/var/www/public/api/api.css

  ###########
  ## REDIS ##
  ###########

  pb-redis:
    container_name: 'pb-redis'
    image: redis
    ports:
      - '6379:6379'

  ################
  ## WEB SOCKET ##
  ################

  pb-websocket:
    command: 'perl ws.pl'
    container_name: 'pb-websocket'
    depends_on:
      - 'pb-mysql-data'
      - 'pb-beanstalkd'
      - 'pb-redis'
    environment:
      - 'KA_NO_MIDDLEWARE=1'
    image: 'perlblue/pb-server'
    ports:
      - '8090:80'
    volumes:
        - ./bin:/home/perlblue/pb-server/bin
        - ./docs:/home/perlblue/pb-server/docs
        - ./etc:/home/perlblue/pb-server/etc
        - ./log:/home/perlblue/pb-server/log
        - ./lib:/home/perlblue/pb-server/lib
        - ./t:/home/perlblue/pb-server/t
        - ./var:/home/perlblue/pb-server/var
